name: navsim-h200
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.3.1
  - nb_conda_kernels
  - pytorch>=2.1.0
  - pytorch-cuda>=12.1
  - pip:
    - torch>=2.1.0
    - torchvision>=0.16.0
    - pytorch-lightning>=2.2.1
    - tensorboard>=2.16.2
    - protobuf==4.25.3
    - nuplan-devkit @ git+https://github.com/motional/nuplan-devkit/@nuplan-devkit-v1.2
    - scikit-learn==1.2.2
    - positional-encodings==6.0.1
    - aioboto3
    - aiofiles
    - bokeh==2.4.3
    - casadi
    - control==0.9.1
    - fiona
    - geopandas>=0.12.1
    - guppy3==3.1.2
    - hydra-core==1.2.0
    - joblib
    - matplotlib
    - nest_asyncio
    - numpy==1.23.4
    - opencv-python==4.9.0.80
    - pandas
    - pillow
    - psutil
    - pyarrow
    - pyinstrument
    - pyogrio
    - pyquaternion>=0.9.5
    - pytest
    - rasterio
    - ray
    - retry
    - rtree
    - scipy
    - selenium
    - setuptools==65.5.1
    - shapely>=2.0.0
    - sqlalchemy==1.4.27
    - sympy
    - tornado
    - tqdm
    - ujson
    - notebook
    - timm 